Description: >
    This template deploys Solodev CMS using Opsworks Chef recipes.

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    InstanceType:
        Description: Web Server EC2 instance type
        Type: String
        Default: m3.medium
        AllowedValues: [t2.small, t2.medium, t2.large, m3.medium, m3.large,
        m3.xlarge, m3.2xlarge, m4.large, m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge,
        c4.large, c4.xlarge, c4.2xlarge, c4.4xlarge, c4.8xlarge, c3.large, c3.xlarge,
        c3.2xlarge, c3.4xlarge, c3.8xlarge, r3.large, r3.xlarge, r3.2xlarge, r3.4xlarge,
        r3.8xlarge, i2.xlarge, i2.2xlarge, i2.4xlarge, i2.8xlarge]
        ConstraintDescription: Please choose a valid instance type.

    VPC:
        Description: Choose which VPC this cluster should be deployed to
        Type: AWS::EC2::VPC::Id

    WebServerSecurityGroup:
        Description: Select the Load Balancer Security Group to use for the cluster hosts
        Type: AWS::EC2::SecurityGroup::Id

    KeyName:
        Default: ''
        Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
        Type: 'AWS::EC2::KeyPair::KeyName'

    AMI:
        Description: Build AMI - This should be passed in
        Type: String

    Subnets:
        Description: Choose which subnets this cluster should be deployed to
        Type: List<AWS::EC2::Subnet::Id>

    FQDN:
        Type: String
        Description: Fully qualified URL for using app.  DNS of FQDN must be pointed to CNAME of ALB.
        Default: ''

    CertificateArn:
        Type: String
        Description: SSL cert for AWS ALB HTTPS listener
        Default: ''

    HostVolumeSize:
        Description: Size in GB of additional non-root volume
        Type: String
        Default: '128'
        AllowedValues:
        - '8'
        - '16'
        - '32'
        - '64'
        - '128'
        - '256'
        - '512'
        - '1024'
        - '2048'
        - '4096'

    BlockVolumeSize:
        Description: Size in GB of additional non-root volume
        Type: String
        Default: '256'
        AllowedValues:
        - '8'
        - '16'
        - '32'
        - '64'
        - '128'
        - '256'
        - '512'
        - '1024'
        - '2048'
        - '4096'

    EFS:
        Description: Choose which EFS this ECS cluster should use for filestorage
        Type: String
        Default: ""

    DatabaseHost:
      Type: String
      Description: The database host

    DatabaseName:
      Type: String
      Description: The database name

    DatabaseUsername:
      Type: String
      Description: The database user name

    DatabasePassword:
      Type: String
      Description: The database user password

    DeploymentType:
        Type: String
        Default: SolodevProduction
        AllowedValues:
        - SolodevFeature
        - SolodevStaging
        - SolodevProduction
        Description: Pick deployment type.

    RestoreBucketName:
        Default: ''
        Description: Name of bucket containing files for restore
        Type: String

    AdminUser:
        Description: CMS Admin User
        Type: String

    AdminPassword:
        Description: CMS Admin Password
        Type: String

    DeletionPolicy:
        Default: 'Snapshot'
        Type: String
        Description: 'Asset Deletion Policy'

    BYOL:
        Default: 'False'
        Type: String

    CookbookURL:
        Type: String

Conditions:
    UseHTTPS: !Not [!Equals [ !Ref CertificateArn, "" ]]
    UseHTTP: !Equals [ !Ref CertificateArn, "" ]

Resources:

    CloudWatchLogsGroup:
        Type: AWS::Logs::LogGroup
        Properties: 
            LogGroupName: !Ref AWS::StackName
            RetentionInDays: 14  

    SolodevBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Join ['-', [!Ref 'EnvironmentName', 'solodev']]
            AccessControl: 'BucketOwnerFullControl'
            Tags:
                -
                  Key: 'Name'
                  Value: !Join ['-', [!Ref 'EnvironmentName', 'S3']]
        DeletionPolicy: 'Delete'

    BackupUser:
        Type: 'AWS::IAM::User'
        Properties:
            Path: /
            Policies:
                - 
                    PolicyName: root
                    PolicyDocument:
                        Statement:
                            - 
                                Effect: Allow
                                Action:
                                    - 'cloudformation:DescribeStackResource'
                                Resource: '*'
                - 
                    PolicyName: backupdef
                    PolicyDocument:
                        Statement: 
                            - 
                                Action: 
                                    - 's3:*'
                                Effect: "Allow"
                                Resource: 
                                    Fn::Join: 
                                    - ""
                                    - 
                                        - "arn:aws:s3:::"
                                        - !Join ['-', [!Ref 'EnvironmentName', 'solodev']]
                            - 
                                Action: 
                                    - 's3:*'
                                Effect: "Allow"
                                Resource: 
                                    Fn::Join: 
                                    - ""
                                    - 
                                        - "arn:aws:s3:::"
                                        - !Join ['-', [!Ref 'EnvironmentName', 'solodev']]
                                        - "/*"

    BackupUserKeys:
        Type: 'AWS::IAM::AccessKey'
        Properties:
            UserName: !Ref BackupUser

    OpsWorksServiceRole:
        Type: 'AWS::IAM::Role'
        Properties:
            AssumeRolePolicyDocument:
                Statement:
                    - 
                        Effect: Allow
                        Principal:
                            Service: opsworks.amazonaws.com
                        Action:
                            - 'sts:AssumeRole'
            Path: /
            Policies:
                - 
                    PolicyName: opsworks-service
                    PolicyDocument:
                        Statement:
                            - 
                                Effect: Allow
                                Action:
                                    - 'rds:*'
                                    - 'ec2:*'
                                    - 'iam:PassRole'
                                    - 'cloudwatch:GetMetricStatistics'
                                    - 'elasticloadbalancing:*'
                                Resource: '*'

    SolodevInstanceRole:
        Type: 'AWS::IAM::Role'
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement: 
                    - 
                        Effect: "Allow"
                        Principal: 
                            Service: 
                                - "ec2.amazonaws.com"
                        Action: 
                        - "sts:AssumeRole"
            Path: /
            Policies:
                - 
                    PolicyName: PowerUserPolicy
                    PolicyDocument:
                        Statement:
                        - 
                            Sid: PowerUserStmt
                            Effect: Allow
                            NotAction: 'iam:*'
                            Resource: '*'

    SolodevInstanceProfile:
        Type: 'AWS::IAM::InstanceProfile'
        Properties:
            Path: /
            Roles:
                - !Ref SolodevInstanceRole

    SolodevApp:
        Type: 'AWS::OpsWorks::App'
        Properties:
            StackId: !Ref SolodevStack
            Name: Solodev
            Type: other
            Attributes:
                DocumentRoot: ' '

    SolodevStack:
        Type: 'AWS::OpsWorks::Stack'
        Properties:
            Name: !Ref 'EnvironmentName'
            DefaultOs: 'Custom'
            ConfigurationManager:
                Name: Chef
                Version: '12'
            ServiceRoleArn: !GetAtt 
                - OpsWorksServiceRole
                - Arn
            DefaultInstanceProfileArn: !GetAtt 
                - SolodevInstanceProfile
                - Arn
            VpcId: !Ref VPC
            DefaultSubnetId: !Select 
                - '0'
                - !Ref Subnets
            UseCustomCookbooks: 'true'
            CustomCookbooksSource:
                Revision: master
                Type: s3
                Url: !Ref CookbookURL
            CustomJson:
                private_dns: 'solodev'
                install:
                    StackName: !Ref 'EnvironmentName'
                    HostedZoneName: !Ref FQDN
                    Region: !Ref 'AWS::Region'

                    AWSAccessKeyId: !Ref BackupUserKeys
                    AWSSecretKey: !GetAtt 
                        - BackupUserKeys
                        - SecretAccessKey

                    ClientName: solodev
                    SoftwareName: solodev
                    DocumentRoot: /var/www
                    ApacheConfDir: /etc/httpd/conf.d
                    DeploymentType: !Ref DeploymentType
                    EnterpriseMode: !Ref BYOL
                    
                    RestoreBucketName: !Ref RestoreBucketName
                    BackupBucketName: !Join ['-', [!Ref 'EnvironmentName', 'solodev']]

                    DBName: !Ref DatabaseName
                    DBHost: !Ref DatabaseHost
                    DBUser: !Ref DatabaseUsername
                    DBPassword: !Ref DatabasePassword
                    EFSHost: !Ref EFS
                    MongoHost: "127.0.0.1"

                    SolodevUser: !Ref AdminUser
                    SolodevPassword: !Ref AdminPassword
                    SolodevTheme: ''
                    SolodevWebsite: ''

    WebServerLayer:
        Type: 'AWS::OpsWorks::Layer'
        DependsOn:
            - SolodevApp
        Properties:
            StackId: !Ref SolodevStack
            Name: !Ref DeploymentType
            Type: custom
            Shortname: solodev-web
            EnableAutoHealing: 'true'
            AutoAssignElasticIps: 'true'
            AutoAssignPublicIps: 'true'
            CustomSecurityGroupIds:
                - !Ref WebServerSecurityGroup
            CustomRecipes:
                Setup:
                    - 'solodev::mount_EFS'
                    - 'solodev::deploy_base'
                    - 'mongo::deploy_mongo'
                    - 'solodev::deploy_scripts'
                    - 'solodev::deploy_duplicity'
                    - 'solodev::client_settings'
                    - 'solodev::deploy_solodev'
                Configure: 
                    - 'mongo::deploy_mongo_single'
                    - 'solodev::update_solodev'
                Deploy:
                    - 'solodev::deploy_solodev'
                    - 'solodev::update_solodev'
                Shutdown: []
                Undeploy: []
            VolumeConfigurations:
                - 
                    MountPoint: /mongo
                    Size: !Ref BlockVolumeSize
                    NumberOfDisks: 1

    SolodevInstance:
        Type: 'AWS::OpsWorks::Instance'
        Properties:
            AmiId: !Ref AMI
            Os: Custom
            StackId: !Ref SolodevStack
            LayerIds:
                - !Ref WebServerLayer
            SubnetId: !Select 
                - '0'
                - !Ref Subnets
            InstanceType: !Ref InstanceType
            RootDeviceType: ebs
            SshKeyName: !Ref KeyName

Outputs:

    DedicatedIP:
        Value: !GetAtt 
        - SolodevInstance
        - PublicIp
        Description: Point DNS A records to this IP and server will redirect to the server CNAME.  If your DNS supports pointing A records to CNAME's please use CNAME instead.